FROM ubuntu:24.04

RUN <<EOF
    apt-get -y update
    apt-get -y install openjdk-17-jdk-headless python3 python3-pip liblapack3 wget curl bash unzip
    rm -rf /var/lib/apt/lists/*
EOF

# Set the working directory
WORKDIR /fuseki

COPY . /fuseki
COPY config.ttl /fuseki
COPY bere-test.ttl /fuseki/bedreflyt.ttl

RUN mkdir -p /fuseki/databases/Bedreflyt
RUN chmod 755 /fuseki/databases/Bedreflyt

# Fetch the latest version and download it
RUN unzip /fuseki/apache-jena-fuseki-5.2.0.zip \
    && mv /fuseki/apache-jena-fuseki-5.2.0 /fuseki/jena-fuseki \
    && rm /fuseki/apache-jena-fuseki-5.2.0.zip

# Execute the command
CMD /fuseki/jena-fuseki/fuseki-server --config /fuseki/config.ttl

# Expose port 3030
EXPOSE 3030